import Foundation
import Testing
@testable import TuringQwenNative

struct TuringQwenPayloadInventoryTests {
    // Goldens generated by Python json.dumps(sort_keys=True,
    // ensure_ascii=False, separators=(",", ":")), then hashlib.sha256.
    @Test func literalCaseNumericAndPunctuationOrderMatchesPython() {
        let rows: [(String, Int, String)] = [
            ("README.md", 1, "a"), ("readme.md", 2, "b"),
            ("file-2.bin", 3, "c"), ("file-10.bin", 4, "d"),
            ("mac_authoring_smoke.wav", 5, "e"),
            ("mac_authoring_smoke_metrics.json", 6, "f"),
            ("nested/Z.json", 7, "0"), ("nested/a.json", 8, "1")
        ]
        let files = Dictionary(uniqueKeysWithValues: rows.map {
            ($0.0, TuringQwenPayloadInventory.Entry(bytes: $0.1, sha256: String(repeating: $0.2, count: 64)))
        })
        #expect(TuringQwenPayloadInventory.fingerprint(files) ==
            "39440a97869310ea57ac483b68b1f9b62b706a1840c7fbb69fd5839f92103b36")
    }

    @Test func unicodeAndControlEscapingMatchesPython() {
        let files: [String: TuringQwenPayloadInventory.Entry] = [
            "Éclair/口😀\u{2028}": .init(bytes: 12_345_678_901, sha256: String(repeating: "a", count: 64)),
            "line\nquote\"slash/\\tab\t\u{00}\u{08}\u{0c}\r\u{1f}":
                .init(bytes: 0, sha256: String(repeating: "b", count: 64))
        ]
        #expect(TuringQwenPayloadInventory.fingerprint(files) ==
            "0f73c0c23d7ecfc3b9ad237ec3f2f9c4b099c68a67a53f915a8709a816a9ff87")
    }

    @Test func emptyInventoryMatchesPython() {
        #expect(TuringQwenPayloadInventory.fingerprint([:]) ==
            "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a")
    }
}
