set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR arm64)

if(NOT DEFINED TURING_APPLE_SDK)
    message(FATAL_ERROR "TURING_APPLE_SDK must be xros or xrsimulator")
endif()

set(TURING_APPLE_SDK "${TURING_APPLE_SDK}" CACHE STRING "Apple SDK" FORCE)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES TURING_APPLE_SDK)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

execute_process(
    COMMAND xcrun --sdk "${TURING_APPLE_SDK}" --show-sdk-path
    OUTPUT_VARIABLE SDK_PATH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

execute_process(
    COMMAND xcrun --sdk "${TURING_APPLE_SDK}" --find clang
    OUTPUT_VARIABLE CLANG_PATH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

set(CMAKE_OSX_SYSROOT "${SDK_PATH}")
set(CMAKE_OSX_ARCHITECTURES arm64)
set(CMAKE_OSX_DEPLOYMENT_TARGET 27.0)
set(CMAKE_C_COMPILER "${CLANG_PATH}")
set(CMAKE_C_FLAGS_INIT "-fvisibility=hidden -ffunction-sections -fdata-sections")
